### PR TITLE
Gametest Part 2: Preliminary refactor every test to use GameTest as the framework.

### LINKED ISSUE #43239: Current integration tests are racy.
Currently, most tests look like this:

```cs
[Test]
public async Task MyTest()
{
    await using var pair = await PoolManager.GetServerClient();

    // ...

    await pair.CleanReturnAsync();
}
```

Let's remove some syntax sugar from this.

```cs
[Test]
public async Task MyTest()
{
    var pair = await PoolManager.GetServerClient();

    try {
        // ...
        await pair.CleanReturnAsync();
    }
    finally
    {
        await pair.DisposeAsync();
    }
}
```

Every test is disposing its pair twice, and relying on the fact DisposeAsync allows this.

This is, however, a problem due to the fact consecutive awaits are *not guaranteed to run immediately*.

In that time, it is possible for the pair to be obtained by another, waiting thread, and then have the pair disposed again *while it is in use.*

The result of this is a test crash.

Fixing this requires properly managing the test pairs with a `[SetUp]` and `[Teardown]` to ensure *one of* the disposal methods run, depending on the test results.

This is resolved through the following PR stack, which must be introduced in order:
- https://github.com/space-wizards/RobustToolbox/pull/6447
- https://github.com/space-wizards/space-station-14/pull/43175
- https://github.com/space-wizards/space-station-14/pull/43182
- https://github.com/space-wizards/space-station-14/pull/43207

They collectively improve test failure reporting (making it easier to diagnose how and why the testframe failed) and fix our resource management problem with room for wider improvement as well.

### PR DESCRIPTION
**Pull request by moonheart08**
## About the PR
this fixes the DisposeAsync test failures and also catches a bunch of other ways tests mismanaged pairs (like not properly returning them on failure),

Blocked on https://github.com/space-wizards/space-station-14/pull/43182/

Discovered https://github.com/space-wizards/space-station-14/issues/43223
Resolves https://github.com/space-wizards/space-station-14/issues/43239

## Why / Balance
~300 content tests all did resource management incorrectly, GameTest does it correctly.

## Technical details
Mostly just changes out pair usage within tests without significantly altering them. Minor alteration is done for things like CVar asserts. Full refactors come in part 3 (in many PRs, not one.)

This changes some tests to be more conservative with their pair configurations, I will get back to them eventually.

This changes a *lot* of tests that previously did not have a connected client to have a connected client. I consider this a plus for coverage, PVS is disabled so any shenanigans should sync with the client.

There is a little bit of wider rewrite-y-ness in here but I gave up on that pretty quick.

## Requirements

- [x] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [x] I have added media to this PR or it does not require an in-game showcase.

## Breaking changes

**Changelog**

### CODE REVIEW

**Comment by moonheart08** [comment]
Preliminary stress testing suggests this PR indeed fixes the main cause of test flaking.

File: Content.IntegrationTests/Tests/GameObjects/Components/EntityPrototypeComponentsTest.cs [hunk 1]
```diff
@@ -131,11 +131,11 @@ public async Task PrototypesHaveKnownComponents()
         [Test]
         public async Task IgnoredComponentsExistInTheCorrectPlaces()
         {
-            await using var pair = await PoolManager.GetServerClient();
+            var pair = Pair;
             var server = pair.Server;
             var client = pair.Client;
             var serverComponents = server.ResolveDependency<IComponentFactory>();
-            var ignoredServerNames = Server.Entry.IgnoredComponents.List;
+            var ignoredServerNames = Content.Server.Entry.IgnoredComponents.List;
```
Comment (Tayrtahn) [inline Content.IntegrationTests/Tests/GameObjects/Components/EntityPrototypeComponentsTest.cs:138]: This doesn't appear to be necessary. Future proofing, or Rider getting excited?

File: Content.IntegrationTests/Tests/Minds/MindTests.Helpers.cs [hunk 2]
```diff
@@ -18,6 +18,14 @@ namespace Content.IntegrationTests.Tests.Minds;
 // This partial class contains misc helper functions for other tests.
 public sealed partial class MindTests
 {
+    // TODO GAMETEST: Rewrite this test to use improved GameTest pair management when I have an API for that figured out.
+    public override PoolSettings PoolSettings => new()
+    {
+        DummyTicker = false,
+        Connected = true,
+        Dirty = true,
+    };
```
Comment (Tayrtahn) [inline Content.IntegrationTests/Tests/Minds/MindTests.Helpers.cs:27]: Does this mean that all of the `MindTests` tests are always flagged as dirty? Would it be possible to just have the tests that need it manually mark the pair themselves?

File: Content.IntegrationTests/Tests/Roles/StartingGearStorageTests.cs
Comment (Tayrtahn) [inline Content.IntegrationTests/Tests/Roles/StartingGearStorageTests.cs:1]: There are a few tests that probably don't actually need to mark themselves dirty, huh? Not something that should be changed in this PR of course; just making a note of it.

File: Content.IntegrationTests/Tests/PostMapInitTest.cs [hunk 3]
```diff
@@ -471,37 +463,18 @@ private static int GetCountLateSpawn<T>(List<EntityUid> gridUids, IEntityManager
...
-                .Select(x => x.ID)
-                .ToHashSet();
-
-            Assert.That(gameMaps.Remove(PoolManager.TestMap));
-
-            Assert.That(gameMaps, Is.EquivalentTo(GameMaps.ToHashSet()), "Game map prototype missing from test cases.");
-
-            await pair.CleanReturnAsync();
-        }
-
```
Comment (Tayrtahn) [inline Content.IntegrationTests/Tests/PostMapInitTest.cs:492]: It's a bit of a weird test sure, but it does make sure that people add new maps to be tested. Obviously it would be nice to handle this automatically, but until then I'm reluctant to just delete this test.

File: Content.IntegrationTests/Tests/StoreTests.cs [hunk 4]
```diff
@@ -32,10 +33,14 @@ public sealed class StoreTests
     - idcard
   - type: Pda
 ";
+
+    // This test is broken and crashes the client if connected.
```
Comment (Tayrtahn) [inline Content.IntegrationTests/Tests/StoreTests.cs]: Maybe leave a TODO or something?

File: Content.IntegrationTests/Tests/PostMapInitTest.cs (hunk 3 above)
Comment (Tayrtahn) [reply Content.IntegrationTests/Tests/PostMapInitTest.cs:492]: Oh wait, I didn't realize that `GameMaps` uses GDS now. Yeah, this test is pointless and can go.

File: Content.IntegrationTests/Tests/Minds/MindTests.Helpers.cs (hunk 2 above)
Comment (moonheart08) [reply Content.IntegrationTests/Tests/Minds/MindTests.Helpers.cs:27]: It's actually entirely impossible for a test to mark itself dirty. I checked. I can just go fix this to use PairSettings now though so I will.

File: Content.IntegrationTests/Tests/GameObjects/Components/EntityPrototypeComponentsTest.cs (hunk 1 above)
Comment (moonheart08) [reply Content.IntegrationTests/Tests/GameObjects/Components/EntityPrototypeComponentsTest.cs:138]: `Server` is the name of a property on GameTest, so this prevents the name ambiguity.

Comment (Tayrtahn) [reply Content.IntegrationTests/Tests/GameObjects/Components/EntityPrototypeComponentsTest.cs:138]: Oh right, very good.

File: Content.IntegrationTests/Tests/Minds/MindTests.Helpers.cs (hunk 2 above)
Comment (moonheart08) [reply Content.IntegrationTests/Tests/Minds/MindTests.Helpers.cs:27]: Actually I doublechecked why I left it this way and the answer is because I'd need to go back and *actually* rewrite all of these tests instead of just patch them. So I won't fix this yet. The TODO applies even to the pre-gametest-changes version of the test.

File: Content.IntegrationTests/Tests/StoreTests.cs (hunk 4 above)
Comment (moonheart08) [reply Content.IntegrationTests/Tests/StoreTests.cs]: Changed to an Ignore.

**Review by Tayrtahn — APPROVED** [review]
Yep, works for me. 

As you've said, these should eventually be converted to use `GameTest` more (which I'd be happy to help with), but I appreciate that this PR's diff is smaller by not doing that yet.

**Review by Fildrance — APPROVED** [review]
Looks valid all in all.
