### PR TITLE
Solutions Refactor Part 1 - Solution Prototypes

### LINKED ISSUE #43192: Solution Entity Prototypes
Solutions currently are spawned using one entity template with their own custom spawning logic to avoid null space initialization issues. The solution is then filled from a component on the parent containing entity, and any components relating to manipulating that solution must be on the parent entity. 

This extremely performance inefficient and provides extreme limitations on the complexity of solutions. 

Instead, solutions should be entity prototypes, which are spawned in containers in the parent entity, to circumvent the complex spawning behavior and allow for solutions to have components. This also will eventually allow solutions to exist outside of containers as interactable entities.

### LINKED ISSUE #43194: Solutions should all be in one container.
Title. 
Having solutions make multiple containers which can only store one entity has been bench marked to be exceptionally performance inefficient for not really any benefit. It's also extremely ugly on the code end so there's no real reason we shouldn't store all solutions for an entity in one container by default.

### LINKED ISSUE #43384: Solution Component outside of containers
Title. This appears to have been an intended feature that was never made.
Instead of all SolutionComponents existing on entities within containers, let the exist attached to entities themselves. That way puddles can be one entity instead of two for example, same with drinks and food, and most things in the game (approximately 98% of entity prototypes can work this way).

### PR DESCRIPTION
**Pull request by Princess-Cheeseballs**
## About the PR

Requires #43314
Resolves #43192
Resolves #43194
Resolves #43384

## Why / Balance

Needed for Nubody and Nuchem. This was also intended to be done by the previous chem/solutions team but they never got around to it it seems. 

98% of prototypes only needed one solution anyways. And this can probably be cut down further with adjustments to Material Composition and such. 

This is a draft because I still need to make the compatibility layer that converts old SolutionContainerManagerComp entities to the new SolutionManager entities. 

## Technical details

Reworked Solution entities such that a SolutionComponent can exist attached to an interactible entity, rather than it always being a separate entity. Moved a comical amount of YAML to facilitate this. 

## Requirements

- [X] I have read and am following the [Pull Request and Changelog Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html).
- [X] I have added media to this PR or it does not require an in-game showcase.

## Breaking changes

`SolutionContainerManagerComponent` has been marked obsolete, use `SolutionComponent` directly on the entity with the solution itself or `SolutionManagerComponent` if your entity requires multiple solutions.

Extra solutions are now all stored in one container dictated by the `SolutionManager`

Bloodstreams have had their capacity doubled from `300u` to `600u`

Solutions have been given standardized sizes and parents for the most part. Solutions are now categorized by size, having 30u of capacity per inventory tile or less. I.E a tiny item has 30u capacity, small 60u, normal 120u ect. Only a few items break this rule. 

The item sizes of many solution containers have changed to reflect their larger capacities. Jugs are now 2x4 large items with 240u capacity, and buckets are now 3x4 huge items with 360u capacity for example. 

The ReagentDispenserBase prototype now has a storage of 16x12 and can store Large items.

**Changelog**

:cl:
- add: You can now boil snails alive in the microwave.
- tweak: Blood volume has been doubled.
- tweak: Many chef recipes have been changed so the final result better matches the ingredients put in. This means overall the nutritional value of the chef's meals have increased.
- tweak: Many chef recipes have had their ingredients changed
- tweak: Most slicable foods now give a lot more slices. 
- tweak: Reagent container sizes have been standardized, at a base of 30 units per inventory square. Most containers can now hold more than they did before.
- tweak: Chemical jugs and bar jugs are now Large (2x4) items.
- tweak: Buckets now hold 360u and are 3x4 items.
- tweak: Nukie medical duffel bag now comes with a bicaridine jug, a mixed puncturase & tranexamic acid jug, a mixed dermaline & pyrazine jug, and a mixed saline & dexalin plus jug.

### CODE REVIEW

**Comment by KashRas2** [comment]
Imagine forks face :skull:

**Comment by Princess-Cheeseballs** [comment]
> Imagine forks face 💀

The day of reckoning for merging bar drink PRs is upon them.
There is gonna be a compatibility layer between the old component and new, just to keep old entities "working" but it will break over time as more stuff relies on the new system. Should give forks plenty of time to switch stuff over though.

File: Content.IntegrationTests/Tests/Chemistry/DrainTest.cs [hunk 1]
```diff
@@ -23,11 +23,11 @@ public sealed class DrainTest : InteractionTest
...
-  suffix: Blood (30u)
+  suffix: Blood
   components:
-  - type: SolutionContainerManager
-    solutions:
-      puddle:
+  - type: Solution
+    id: puddle
+    solution:
         maxVol: 1000
```
Comment (sowelipililimute) [inline Content.IntegrationTests/Tests/Chemistry/DrainTest.cs]: don't forget to adjust indentation on following lines

File: Content.IntegrationTests/Tests/Chemistry/SolutionRoundingTest.cs [hunk 2]
```diff
@@ -20,10 +20,10 @@ public sealed class SolutionRoundingTest
...
   id: SolutionRoundingTestContainer
   components:
-  - type: SolutionContainerManager
-    solutions:
-      beaker:
-        maxVol: 100
+  - type: Solution
+    id: beaker
+    solution:
+       maxVol: 100
```
Comment (sowelipililimute) [inline Content.IntegrationTests/Tests/Chemistry/SolutionRoundingTest.cs]: ditto

File: Content.IntegrationTests/Tests/Chemistry/SolutionSystemTests.cs [hunk 3]
```diff
@@ -19,10 +19,10 @@ public sealed class SolutionSystemTests
...
   id: SolutionTarget
   components:
-  - type: SolutionContainerManager
-    solutions:
-      beaker:
-        maxVol: 50
+  - type: Solution
+    id: beaker
+    solution:
+       maxVol: 50
```
Comment (sowelipililimute) [inline Content.IntegrationTests/Tests/Chemistry/SolutionSystemTests.cs]: ditto

File: Content.IntegrationTests/Tests/Chemistry/TryAllReactionsTest.cs [hunk 4]
```diff
@@ -19,11 +19,10 @@ public sealed class TryAllReactionsTest
...
   components:
-  - type: SolutionContainerManager
-    solutions:
-      beaker:
-        maxVol: 50
-        canMix: true";
+  - type: Solution
+    id: beaker
+    solution:
+       maxVol: 120";
```
Comment (sowelipililimute) [inline Content.IntegrationTests/Tests/Chemistry/TryAllReactionsTest.cs]: ditto

File: Content.IntegrationTests/Tests/Fluids/AbsorbentTest.cs [hunk 5]
```diff
@@ -34,18 +34,18 @@ public sealed class AbsorbentTest
   components:
   - type: Absorbent
     useAbsorberSolution: true
-  - type: SolutionContainerManager
-    solutions:
-      absorbed:
+  - type: Solution
+    id: absorbed
+    solution:
```
Comment (sowelipililimute) [inline Content.IntegrationTests/Tests/Fluids/AbsorbentTest.cs:40]: ditto

File: Content.IntegrationTests/Tests/Fluids/AbsorbentTest.cs [hunk 6]
```diff
@@ -34,18 +34,18 @@ public sealed class AbsorbentTest
...
 - type: entity
   name: {RefillableDummyId}
   id: {RefillableDummyId}
   components:
-  - type: SolutionContainerManager
-    solutions:
-      refillable:
+  - type: Solution
+    id: refillable
+    solution:
```
Comment (sowelipililimute) [inline Content.IntegrationTests/Tests/Fluids/AbsorbentTest.cs:49]: ditto

File: Content.IntegrationTests/Tests/Fluids/AbsorbentTest.cs [hunk 7]
```diff
@@ -54,9 +54,9 @@ public sealed class AbsorbentTest
   name: {SmallRefillableDummyId}
   id: {SmallRefillableDummyId}
   components:
-  - type: SolutionContainerManager
-    solutions:
-      refillable:
+  - type: Solution
+    id: refillable
+    solution:
         maxVol: 20
```
Comment (sowelipililimute) [inline Content.IntegrationTests/Tests/Fluids/AbsorbentTest.cs]: ditto

File: Content.Shared/Body/Components/BloodstreamComponent.cs [hunk 8]
```diff
@@ -148,10 +148,10 @@ public sealed partial class BloodstreamComponent : Component
     /// Defines which reagents are considered as 'blood' and how much of it is normal.
     /// </summary>
     /// <remarks>
-    /// Slime-people might use slime as their blood or something like that.
+    /// Default is human blood at 5 liters (600u) of blood.
     /// </remarks>
     [DataField, AutoNetworkedField]
-    public Solution BloodReferenceSolution = new([new("Blood", 300)]);
+    public Solution BloodReferenceSolution = new([new("Blood", 600)]);
```
Comment (sowelipililimute) [inline Content.Shared/Body/Components/BloodstreamComponent.cs:154]: missing a changelog entry since this doubles blood volume

File: Content.Shared/Chemistry/Components/SolutionManager/SolutionContainerManagerComponent.cs [hunk 9]
```diff
@@ -5,10 +5,9 @@
...
 
 /// <summary>
-/// <para>A map of the solution entities contained within this entity.</para>
-/// <para>Every solution entity this maps should have a <see cref="SolutionComponent"/> to track its state and a <see cref="ContainedSolutionComponent"/> to track its container.</para>
+/// TODO: DELET THIS ONLY EXISTS TO MAKE GAME RUN!!!!
 /// </summary>
-[RegisterComponent, NetworkedComponent, AutoGenerateComponentState]
+[RegisterComponent]
 [Access(typeof(SharedSolutionContainerSystem))]
 public sealed partial class SolutionContainerManagerComponent : Component
```
Comment (sowelipililimute) [inline Content.Shared/Chemistry/Components/SolutionManager/SolutionContainerManagerComponent.cs]: why is this still here? there's no systems referencing it and no YAML either

File: Content.Shared/Chemistry/Components/SolutionManager/SolutionManagerComponent.cs [hunk 10]
```diff
@@ -0,0 +1,36 @@
...
+    /// <summary>
+    /// A cache of solutions currently attached to this entity.
+    /// </summary>
+    [ViewVariables]
+    public Dictionary<string, Entity<SolutionComponent>> Solutions = new ();
+
+    /// <summary>
+    /// A list of solution entities to spawn when this component starts up.
+    /// </summary>
+    [DataField("solutions")]
```
Comment (sowelipililimute) [inline Content.Shared/Chemistry/Components/SolutionManager/SolutionManagerComponent.cs]:
```suggestion
    [DataField("solutions", readOnly: true)]
```

File: Content.Shared/Chemistry/Components/SolutionManager/SolutionManagerComponent.cs [hunk 11]
```diff
@@ -0,0 +1,36 @@
...
+    /// The names of the container for solutions attached to this entity.
+    /// </summary>
+    [DataField, AutoNetworkedField]
+    public string Container = DefaultContainerId;
+
+    /// <summary>
+    /// A cache of solutions currently attached to this entity.
+    /// </summary>
+    [ViewVariables]
+    public Dictionary<string, Entity<SolutionComponent>> Solutions = new ();
```
Comment (sowelipililimute) [inline Content.Shared/Chemistry/Components/SolutionManager/SolutionManagerComponent.cs:30]:
```suggestion
    [ViewVariables]
    [Access(typeof(SharedSolutionContainerSystem), Other = AccessPermissions.None)]
    public Dictionary<string, Entity<SolutionComponent>> Solutions = new ();
```
make caching an implementation detail of the system

File: Content.Shared/Chemistry/EntitySystems/SharedSolutionContainerSystem.Compatibility.cs [hunk 12]
```diff
@@ -0,0 +1,16 @@
+﻿using Content.Shared.Chemistry.Components.SolutionManager;
+
+namespace Content.Shared.Chemistry.EntitySystems;
+
+/// <summary>
+/// This exists so that entity prototypes and maps with <see cref="SolutionContainerManagerComponent"/> can load.
+/// All methods in this file will be deleted in the indeterminate future, it is here to give you time to move to the new system.
+/// You have been warned.
+/// </summary>
```
Comment (sowelipililimute) [inline Content.Shared/Chemistry/EntitySystems/SharedSolutionContainerSystem.Compatibility.cs:12]: this isn't actually any compatibility API, and this comment should be moved to `SolutionContainerManagerComponent`.

File: Content.Shared/Chemistry/Components/SolutionManager/SolutionContainerManagerComponent.cs [hunk 13]
```diff
@@ -31,6 +30,6 @@ public sealed partial class SolutionContainerManagerComponent : Component
     /// <remarks>
     /// Should be null after mapinit.
     /// </remarks>
-    [DataField, AutoNetworkedField]
-    public Dictionary<string, Solution>? Solutions = null;
+    [DataField]
+    public Dictionary<string, Solution>? Solutions;
```
Comment (sowelipililimute) [inline Content.Shared/Chemistry/Components/SolutionManager/SolutionContainerManagerComponent.cs:38]: gut the datafields so yaml linting will complain appropriately

**Review by sowelipililimute — CHANGES_REQUESTED** [review]

**Comment by Golubgik** [comment]
need holy shit

**Comment by Princess-Cheeseballs** [comment]
Made 2 spinoff PRs
https://github.com/space-wizards/space-station-14/pull/43447
https://github.com/space-wizards/space-station-14/pull/43448

Something something atomization.

**Comment by Beansies** [comment]
I think that changing the jug and bar jug sizes are going to be catastrophic to Nuclear operatives with space so limited I don't think they will be able to carry enough meds. cutting the number of jugs they can carry by half will be a big upset. maybe 2x3 180u jugs? or purchasable syndicate jugs that are basically current bar jugs? 2x2 300u.

**Comment by Princess-Cheeseballs** [comment]
> I think that changing the jug and bar jug sizes are going to be catastrophic to Nuclear operatives with space so limited I don't think they will be able to carry enough meds. cutting the number of jugs they can carry by half will be a big upset. maybe 2x3 180u jugs? or purchasable syndicate jugs that are basically current bar jugs? 2x2 300u.

If a 2x3 container is needed it can be added. Right now I'm focusing more on having some sanity to balancing containers over maintaining current balance. 
If it's a bad enough blow to Nukies I wouldn't be opposed to just giving them a jug full of Omni or something for free since that condenses their medicine a lot.

**Review by sowelipililimute — APPROVED** [review]
this looks good, i love a -3kloc diff :]

**Comment by memengineer25** [comment]
hold on a second, does increasing jug size not just shoot nukies (and chemtags) dead in the street???? why was this speedmerged??? this has insanely large balance ramifications that are completely unaddressed and have been completely ignored with zero discussion
The backend changes are fine - no issues there - but you're slipping in balance ruining changes to your backend improvements for no reason

**Comment by ScarKy0** [comment]
> why was this speedmerged???

This PR has been opened for longer than a month it is definitely not a speedmerge
And I believe these changes had to have been made sooner or later, seeing how much of a mess container capacities have been for so long

**Comment by memengineer25** [comment]
> seeing how much of a mess container capacities have been for so long
 
 You have to actually untangle the mess or go around it instead because other things _rely_ on the mess working as it does. The game has had things added and been balanced with the existing reagant storage sizes in mind and steps need to actually be taken to _address_ that, not completely ignore it and act like you're fixing more problems than you're causing.

If this was paired with something like an increase in healing densities for chems (which would would probably be a good thing to do in general just because injecting someone with like half a liter of ANYTHING much less pure chemicals is weird) then it could probably work, but you have to actually try and think about what systems your changes will affect before making them.

**Comment by Beansies** [comment]
> hold on a second, does increasing jug size not just shoot nukies (and chemtags) dead in the street???? why was this speedmerged??? this has insanely large balance ramifications that are completely unaddressed and have been completely ignored with zero discussion
> 
> i don't care about the backend changes, those are fine, but you're slipping in balance ruining changes to your backend improvements for no reason

I agree with the sentiment about changing the jug sizes. The response when I raised the concern was 

> If a 2x3 container is needed it can be added. Right now I'm focusing more on having some sanity to balancing containers over maintaining current balance.
If it's a bad enough blow to Nukies I wouldn't be opposed to just giving them a jug full of Omni or something for free since that condenses their medicine a lot.

It seems the plan is to ship now and worry about balance changes later. I’m not too big a fan of that approach and while I appreciate the hard work being done on the backend, I think there is going to be a lot of backlash. I’d say to balance this you would need to increase either the size of bar jugs in inventories so bartenders don’t get screwed on having less drinks, leave regular jugs, shakers and buckets alone or at the very least give the uplink the option of purchasing more efficient jugs, and maybe start the corpsman off with the enhanced jugs. I quite liked the intricacies of finding the optimal storage containers throughout my play time and I am deeply saddened to see them go. I felt more natural for things to be differently sized and hold different amounts. Like a syringe and bottle. Both 1x1 but it makes sense the bottle holds more.

**Comment by Minemoder5000** [comment]
> The game has had things added and been balanced with the existing reagant storage sizes in mind and steps need to actually be taken to _address_ that, not completely ignore it and act like you're fixing more problems than you're causing.

This game is a playtest in active development. Doing everything all at once will lead to failure, that's why newmed was in limbo for so long. It was one person reworking the entirety of medical all at once, instead of gradual steps. Things can and will be tweaked. I personally think this is better for the game. The corpsman has to choose how much of what chems to bring. Bigger or smaller containers for the chems.

As for chemist antagonists, good. They shouldn't be able to solo the entire station because they have chems. The medical rework will make sure of that, anyway.

**Comment by memengineer25** [comment]
> This game is a playtest in active development. Doing everything all at once will lead to failure, that's why newmed was in limbo for so long.

Things being in limbo for so long is exactly why things _need_ to be done all at once. Otherwise you end up with dozens of permanent temporary solutions that make them game vastly worse.

> The corpsman has to choose how much of what chems to bring.

They already do this. Chem storage is already an issue for nukie medics and now they can bring like two jugs tops. This isn't going to have them make meaningful choices, it's going to limit their creativity because now they're just going to make one or two things. And is also going to nerf them to shit.

> As for chemist antagonists, good. They shouldn't be able to solo the entire station because they have chems. The medical rework will make sure of that, anyway.

chemtags should be rewarded for being good at the game. they're killable if you know what you're doing.

**Comment by Beansies** [comment]
> > The game has had things added and been balanced with the existing reagant storage sizes in mind and steps need to actually be taken to _address_ that, not completely ignore it and act like you're fixing more problems than you're causing.
> 
> This game is a playtest in active development. Doing everything all at once will lead to failure, that's why newmed was in limbo for so long. It was one person reworking the entirety of medical all at once, instead of gradual steps. Things can and will be tweaked. I personally think this is better for the game. The corpsman has to choose how much of what chems to bring. Bigger or smaller containers for the chems.
> 
> As for chemist antagonists, good. They shouldn't be able to solo the entire station because they have chems. The medical rework will make sure of that, anyway.

This seems like a trial by fire approach and while I hope it goes well with the playerbase I do not think it will. I believe it will drive many players away to different forks and they won’t check back in later to see if thing got better. They will leave and won’t come back like many people on the forums said about the old vulture playerbase. I love this game and I would hate to see the servers die over this. It seems there is a goal to get rid of anything that can optimize player storage such as making jackets 2x3 in the bag so they don’t let you carry things more efficiently.

**Comment by memengineer25** [comment]
> It seems there is a goal to get rid of anything that can optimize player storage

Taking away anything players can do to optimize is a consistent pattern with this team, it's not surprising it's hit this too

> I hope it goes well with the playerbase I do not think it will.

Yeah it turns out players don't really like it when you make the game worse because you'll TOTALLY improve it later

**Comment by Minemoder5000** [comment]
> I believe it will drive many players away to different forks and they won’t check back in later to see if thing got better.

That's fine. Players can choose to go to forks with content they like. Wizden will survive. Just as they always have.

**Comment by memengineer25** [comment]
> That's fine. Players can choose to go to forks with content they like. Wizden will survive. Just as they always have.

This ignores the fact that wizden is upstream.

It would be fine if wizden was a downstream, or if wizden only pushed their major changes downstreams when they were actually finished instead of half-baked, but neither of those are the case.

**Comment by Beansies** [comment]
> That's fine. Players can choose to go to forks with content they like. Wizden will survive. Just as they always have.

I don’t think that taking the approach of disregarding how players feel about changes and being apathetic to where they play is very conducive to maintaining or growing the active playerbase on wizden servers.

**Comment by Minemoder5000** [comment]
> This ignores the fact that wizden is upstream.

Forks can choose to rebalance things themselves. Or not merge changes made upstream.

> I don’t think that taking the approach of disregarding how players feel about changes and being apathetic to where they play is very conducive to maintaining or growing the active playerbase on wizden servers.

I trust the maintainers. They have a vision and know where they want to take the game. The loud players will disagree, make noise, then either stop complaining about it or leave.

Space Station by nature is a game where multiple forks will be made, and people will gravitate towards the content they like. I'm sure the exact same arguments have been made on forks on SS13. People dislike a change. People leave for another fork, or make their own. People are now happier with the content, wherever they end up.

**Comment by memengineer25** [comment]
> I trust the maintainers. They have a vision and know where they want to take the game. The loud players will disagree, make noise, then either stop complaining about it or leave.

driving away your playerbase is not a flex

**Comment by Pok27** [comment]
I don't think this is such an important balance change that it would be necessary to delay the PR, which significantly helps the project as a whole, for the sake of discussing it.

**Comment by Minemoder5000** [comment]
> driving away your playerbase is not a flex

You are one person out of a few hundred, you can't speak for everyone. Players will leave. New players will join. Just as they have for the last decade.

**Comment by Beansies** [comment]
> I trust the maintainers. They have a vision and know where they want to take the game. The loud players will disagree, make noise, then either stop complaining about it or leave.

It’s the or leave part that worries me. When players leave they don’t look back. If this is going to get pushed to the master branch I think the best way to minimize damage is to put a disclaimer that it is for testing and balance changes will be made accordingly. I remember one change that linked to the forums after every round ended. If something like that is reimplemented players would be more likely to give it time otherwise I fear the days of 80 pop servers are over, and lizard and leviathan are going to have to merge to keep high pop numbers.

**Comment by memengineer25** [comment]
> I don't think this is such an important balance change that it would be necessary to delay the PR, which significantly helps the project as a whole, for the sake of discussing it.

No need to delay the PR, just remove the random balance change snuck in the back door. Aside from the solution container size changes this does seem like a good change

**Comment by memengineer25** [comment]
> You are one person out of a few hundred, you can't speak for everyone. Players will leave. New players will join. Just as they have for the last decade.

A game for everyone is a game for no one, but a game for no one is... also a game for no one.
