### PR TITLE
fix antag selection being evil

### LINKED ISSUE #27425: antag selection is selecting people to be nukies even with it unselected and locked
## Description

https://discord.com/channels/310555209753690112/1233970230749954068
person reported to have gotten both operative and commander
image

**Reproduction**

**Screenshots**

**Additional context**

### LINKED ISSUE #28196: antag selection can pick players in the lobby
## Description
:blunt: it then throws but still how

### PR DESCRIPTION
**Pull request by deltanedas**
## About the PR
remove the shitcode that made it pick people IN THE LOBBY and that dont meet requirements for any listed antag role in the rule

## Why / Balance
idk being a traitor in ooc sounds bad, if it even worked and didnt just crash the server
fixes #27425 and fixes #28196

## Media
wyci
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes
no

**Changelog**
:cl:
- fix: Fixed being picked for antag roles while in the lobby or not opted in.

### CODE REVIEW

File: Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs [hunk 1]
```diff
@@ -50,6 +50,9 @@ public async Task TryStopNukeOpsFromConstantlyFailing()
         var invSys = server.System<InventorySystem>();
         var factionSys = server.System<NpcFactionSystem>();
 
+        // test urist is a noob let him be nukie
+        server.CfgMan.SetCVar(CCVars.GameRoleTimers, false);
+
```
Comment (metalgearsloth) [inline Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs:55]: Shouldn't this just be disabled globally anyway.

Comment (deltanedas) [reply Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs:55]: the cvar in code is true by default but on debug(?) its set to false somehow except in tests idk

also itd probably break a lot of servers

Comment (deltanedas) [reply Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs:55]: also to fix test for real how to make urist opt into being commander

File: Content.Server/Antag/AntagSelectionSystem.cs [hunk 2]
```diff
@@ -345,13 +340,9 @@ public AntagSelectionPlayerPool GetPlayerPool(Entity<AntagSelectionComponent> en
...
                 fallbackList.Add(session);
             }
-            else
-            {
-                unwantedList.Add(session);
-            }
         }
 
-        return new AntagSelectionPlayerPool(new() { preferredList, fallbackList, unwantedList, invalidList });
+        return new AntagSelectionPlayerPool(new() { preferredList, fallbackList });
```
Comment (VasilisThePikachu) [inline Content.Server/Antag/AntagSelectionSystem.cs:345]: When i was trying to fix this myself i basically did the same thing. My only consairn and why i never made a pr was cause. What happens if we got no one in the prefferedlist or fallbacklist? Are we starting the gamemode without any antags. This resulting in a broken gamerule/greenshift.

File: Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs (hunk 1 above)
Comment (ElectroJr) [reply Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs:55]: Tests don't automatically reset cvars, so you have to manually reset the cvar back to its original value at the end of the test, or you need to change the value for all tests in `PoolManager.Cvars.cs`.

File: Content.Server/Antag/AntagSelectionSystem.cs (hunk 2 above)
Comment (VasilisThePikachu) [reply Content.Server/Antag/AntagSelectionSystem.cs:345]: Afaik it also picks people at random in game not just in the lobby (look at sleeper agents. There are reports that players get sleeper agent given to them when they never opted in)

File: Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs (hunk 1 above)
Comment (deltanedas) [reply Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs]: cvar is now being reset, only issue is still the opt in part to fix tests

File: Content.Server/Antag/AntagSelectionSystem.cs (hunk 2 above)
Comment (deltanedas) [reply Content.Server/Antag/AntagSelectionSystem.cs:345]: yes this fixes that since it wont pick anyone that didnt opt in

File: Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs [hunk 3]
```diff
@@ -50,6 +50,10 @@ public async Task TryStopNukeOpsFromConstantlyFailing()
         var invSys = server.System<InventorySystem>();
         var factionSys = server.System<NpcFactionSystem>();
 
+        // test urist is a noob let him be nukie
+        Assert.That(server.CfgMan.GetCVar(CCVars.GameRoleTimers), Is.True);
```
Comment (ElectroJr) [inline Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs:54]: Ah, apparently its already disabled in tests by default

Comment (deltanedas) [reply Content.IntegrationTests/Tests/GameRules/NukeOpsTest.cs:54]: bruh????

**Comment by ElectroJr** [comment]
You probably have to update the tests so that you can specify preferences for clients, so that they can opt into the nukie role?

File: Content.IntegrationTests/Tests/GameRules/AntagPreferenceTest.cs [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+
+namespace Content.IntegrationTests.Tests.GameRules;
+
+// Once upon a time, players in the lobby weren't ever considered eligible for antag roles.
+// Lets not let that happen again.
+[TestFixture]
+public sealed class AntagPreferenceTest
+{
+    /// <summary>
+    /// Check that a nuke ops game mode can start without issue. I.e., that the nuke station and such all get loaded.
```
Comment (deltanedas) [inline Content.IntegrationTests/Tests/GameRules/AntagPreferenceTest.cs:20]: copy paste ops

Comment (ElectroJr) [reply Content.IntegrationTests/Tests/GameRules/AntagPreferenceTest.cs]: ops

**Comment by ElectroJr** [comment]
I pushed a few commits, most notably:

[Allow tests to modify antag preferences](https://github.com/space-wizards/space-station-14/pull/28197/commits/34ea5b352ae6c536a63be97e8fd705e5fd82f4bb)
makes the nukie test change the antag preferences to opt into nuke ops 

[Fix antag selection](https://github.com/space-wizards/space-station-14/pull/28197/commits/0781d5a799f40107cae2aeb7e48063f08e1c30f7)
Fixes what I think was actually going wrong, because it was causing all players in the lobby to be considered ineligible for antag roles at round start. So everyone was considered ineligible, which would've made it much more likely for people to get picked with the role disabled, as usually it should've only happened on low pop servers or on a server full of pacifists. Though I still think forcing people to be antags against their will is bad so the unwanted & invalid lists should still get removed

**Comment by Plykiya** [comment]
not only can antag selection pick people who are just waiting in the lobby, it also has a chance to make ghosts antags as well

**Review by EmoGarbage404 — APPROVED** [review]

**Comment by GroggleG** [comment]
Evil antag selection: I will work properly and not run like shit.
On a serious note is there actually good progress on the fix?

File: Content.Server/Antag/AntagSelectionSystem.cs (hunk 2 above)
Comment (deltanedas) [reply Content.Server/Antag/AntagSelectionSystem.cs:345]: the majority of the issue is people that arent opted in getting picked, invalid is only really picked in a dev environment. nukies making ghost roles for missing players wyci

**Comment by ElectroJr** [comment]
> On a serious note is there actually good progress on the fix?

I think it fixes the selection bugs? but its hard to know because its pretty hard to test properly.

> keep the unwanted list but not the invalid one at least until we have ways of setting up ghost roles and other rules properly.

I don't think there's any situation where you want to force someone to be an antag if they explicitly opted out of that role. That is probably just going to lead to people leaving the server.

**Comment by EmoGarbage404** [comment]
> I don't think there's any situation where you want to force someone to be an antag if they explicitly opted out of that role. That is probably just going to lead to people leaving the server.

realistically it doesnt happen much and i think its preferable when we dont have a system that resolves not having players for a given antag.

**Comment by deltanedas** [comment]
it happens enough to have like 4 issues opened
this is especially an issue on lowpop where theres less players to begin with, much more likely to have people that arent opted in

**Comment by EmoGarbage404** [comment]
> it happens enough to have like 4 issues opened

that's because the selection has been bugged. that's been the old behavior for literal ages and the amount of times it happens normally is extremely low

**Comment by ElectroJr** [comment]
> realistically it doesnt happen much and i think its preferable when we dont have a system that resolves not having players for a given antag.

I'd still rather it not pick anyone than force an unwilling player that will probably just leave. Eventually the game rule system should be reworked so that at bare minimum the rule should notify any active admins somehow that it failed to select players and they can sort it out. Though ideally the rule just wouldn't even be picked.

**Comment by EmoGarbage404** [comment]
fairnuff i dont care to push on it
