### PR TITLE
Fix clicking a locker while inside of said locker

### LINKED ISSUE #1535: Attacking while inside a locker/scanner hits entities outside of the locker/scanner
1. Go into a locker
2. Spawn a damageable entity next to
3. Punch it

### LINKED ISSUE #3031: Click-attack through lockers
When in a locker/disposals unit/etc you can click attack other nearby entities through the container.

### PR DESCRIPTION
**Pull request by ShadowCommander**
Fixes #1535 the right way.
Fixes #3031

## About the PR 

**Changelog**

:cl:
- fix: Fixed clicking a locker when the player is inside of said locker.

### CODE REVIEW

**Review by PaulRitter — CHANGES_REQUESTED** [review]

**Comment by ShadowCommander** [comment]
Added a test, but I needed to change UserInteraction and DoAttack to public. If this is a problem I can probably make a new method that calls each.

File: Content.IntegrationTests/Tests/Interaction/Click/InteractionSystemTests.cs [hunk 1]
```diff
@@ -0,0 +1,141 @@
...
+            var entityManager = server.ResolveDependency<IEntityManager>();
+            var mapManager = server.ResolveDependency<IMapManager>();
+
+            IEntity origin = null;
+            IEntity other = null;
+            IEntity containerEntity = null;
+            IContainer container = null;
+            IComponent component = null;
+            EntityCoordinates entityCoordinates = default;
+            MapCoordinates mapCoordinates = default;
```
Comment (PaulRitter) [inline Content.IntegrationTests/Tests/Interaction/Click/InteractionSystemTests.cs:68]: these three get assigned an are then never used.

**Review by PaulRitter — CHANGES_REQUESTED** [review]

**Review by PaulRitter — APPROVED** [review]
